apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factorio-server-charts.fullname" . }}
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: {{ template "factorio-server-charts.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "factorio-server-charts.fullname" . }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "factorio-server-charts.fullname" . }}
    spec:
      securityContext:
        runAsUser: 845
        runAsGroup: 845
        fsGroup: 845
      containers:
      - name: {{ template "factorio-server-charts.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
        ports:
        - name: factorio
          containerPort: {{ .Values.service.port }}
          protocol: UDP
        - containerPort: {{ .Values.rcon.port }}
          protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: datadir
            mountPath: /factorio
          - name: {{ template "factorio-server-charts.fullname" . }}-serversettingsconfig
            mountPath: {{ .Values.factorioServer.config_path | quote }}
        env:
        - name: UPDATE_MODS_ON_START
          value: {{ .Values.factorioServer.update_mods_on_start | quote }}
        - name: INSTANCE_NAME
          value: {{ .Values.server_settings.name | quote }}
        - name: INSTANCE_DESC
          value: {{ .Values.server_settings.description | quote }}
        - name: SAVE_NAME
          value: {{ .Values.factorioServer.save_name | quote }}
        - name: GENERATE_NEW_SAVE
          value: {{ .Values.factorioServer.generate_new_save | quote }}
        - name: LOAD_LATEST_SAVE
          value: {{ .Values.factorioServer.load_latest_save | quote }}
        - name: PORT
          value: {{ .Values.service.port | quote }}
        - name: CONFIG
          value: {{ .Values.factorioServer.config_path | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: datadir
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.dataDir.existingClaim }} {{.Values.persistence.dataDir.existingClaim}} {{ else }}{{ template "factorio-server-charts.fullname" . }}-datadir {{ end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: {{ template "factorio-server-charts.fullname" . }}-serversettingsconfig
          configMap:
            name: {{ template "factorio-server-charts.fullname" . }}-serversettingsconfig

